# add GEOCOUNTRY table

# --- !Ups

CREATE TABLE IF NOT EXISTS GEOCOUNTRY (
  ID BIGINT(20) NOT NULL auto_increment,
  COUNTRYCODE VARCHAR(2) NOT NULL default '',
  NAME VARCHAR(200) NOT NULL default '',
  PRIMARY KEY (ID),
  UNIQUE KEY (COUNTRYCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE GEOCOUNTRY;