# add INDUSTRY table

# --- !Ups

CREATE TABLE IF NOT EXISTS INDUSTRY (
  ID BIGINT(20) NOT NULL auto_increment,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (NAME)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE INDUSTRY;