# add EMPLOYER table

# --- !Ups

CREATE TABLE IF NOT EXISTS EMPLOYER (
  ID BIGINT(20) NOT NULL auto_increment,
  NAME VARCHAR(50) NOT NULL,
  INDUSTRY_ID BIGINT(20) NOT NULL,
  WEBSITE VARCHAR(255) DEFAULT NULL,
  PHONE VARCHAR(50) DEFAULT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  STATECODE VARCHAR(8) NOT NULL,
  POSTALCODE VARCHAR(20) NOT NULL,
  COUNTRYCODE VARCHAR(2) NOT NULL,
  CATEGORY VARCHAR(75) DEFAULT NULL,
  SUBCATEGORY VARCHAR(75) DEFAULT NULL,
  YELP_ID VARCHAR(100) DEFAULT NULL,
  FACTUAL_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (YELP_ID),
  UNIQUE KEY (FACTUAL_ID),
  CONSTRAINT FOREIGN KEY (INDUSTRY_ID) REFERENCES INDUSTRY (ID) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE EMPLOYER;