# populte GEOSTATE table

# --- !Ups

INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Alberta', 'AB');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'British Columbia', 'BC');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Manitoba', 'MB');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'New Brunswick', 'NB');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Newfoundland and Labrador', 'NL');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Northwest Territories', 'NT');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Nova Scotia', 'NS');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Nunavut', 'NU');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Ontario', 'ON');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Prince Edward Island', 'PE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Québec', 'QC');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Saskatchewan', 'SK');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('CA', 'Yukon Territory', 'YT');

INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Alaska', 'AK');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Alabama', 'AL');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'American Samoa', 'AS');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Arizona', 'AZ');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Arkansas', 'AR');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'California', 'CA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Colorado', 'CO');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Connecticut', 'CT');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Delaware', 'DE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'District of Columbia', 'DC');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Federated States of Micronesia', 'FM');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Florida', 'FL');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Georgia', 'GA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Guam', 'GU');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Hawaii', 'HI');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Idaho', 'ID');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Illinois', 'IL');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Indiana', 'IN');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Iowa', 'IA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Kansas', 'KS');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Kentucky', 'KY');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Louisiana', 'LA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Maine', 'ME');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Marshall Islands', 'MH');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Maryland', 'MD');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Massachusetts', 'MA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Michigan', 'MI');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Minnesota', 'MN');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Mississippi', 'MS');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Missouri', 'MO');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Montana', 'MT');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Nebraska', 'NE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Nevada', 'NV');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'New Hampshire', 'NH');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'New Jersey', 'NJ');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'New Mexico', 'NM');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'New York', 'NY');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'North Carolina', 'NC');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'North Dakota', 'ND');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Northern Mariana Islands', 'MP');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Ohio', 'OH');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Oklahoma', 'OK');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Oregon', 'OR');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Palau', 'PW');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Pennsylvania', 'PA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Puerto Rico', 'PR');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Rhode Island', 'RI');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'South Carolina', 'SC');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'South Dakota', 'SD');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Tennessee', 'TN');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Texas', 'TX');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Utah', 'UT');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Vermont', 'VT');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Virgin Islands', 'VI');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Virginia', 'VA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Washington', 'WA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'West Virginia', 'WV');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Wisconsin', 'WI');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Wyoming', 'WY');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Africa', 'AE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Americas (except Canada)', 'AA');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Canada', 'AE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Europe', 'AE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Middle East', 'AE');
INSERT INTO GEOSTATE (COUNTRYCODE, NAME, STATECODE) VALUES ('US', 'Armed Forces Pacific', 'AP');

# --- !Downs

TRUNCATE TABLE GEOSTATE;