# add USER table

# --- !Ups

CREATE TABLE IF NOT EXISTS USER (
  ID BIGINT(20) NOT NULL auto_increment,
  EMAIL VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(50) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  STATECODE VARCHAR(8) NOT NULL,
  POSTALCODE VARCHAR(20) NOT NULL,
  COUNTRYCODE VARCHAR(2) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (EMAIL),
  CONSTRAINT FOREIGN KEY (COUNTRYCODE) REFERENCES GEOCOUNTRY (COUNTRYCODE) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE USER;