# populate TITLE table

# --- !Ups

# Kitchen
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Chef', 'Executive Chef', 1, 1, 2);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Chef de Cuisine', 'Chef de Cuisine', 1, 1, 3);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Sous Chef', 'Sous Chef', 1, 1, 4);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Chef de Partie', 'Chef de Partie', 1, 1, 5);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Line Cook', 'Line Cook', 1, 1, 6);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Prep Cook', 'Prep Cook', 1, 1, 7);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Dishwasher', 'Dishwasher', 1, 1, 8);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Pastry Chef', 'Dishwasher', 1, 1, 5);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Pastry Cook', 'Dishwasher', 1, 1, 6);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Butcher', 'Butcher', 1, 1, 5);

# Front of the house
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Owner', 'Restaurant Owner', 1, 2, 1);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('General Manager', 'General Manager', 1, 2, 2);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Assistant GM', 'Assistant General Manager', 1, 2, 3);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Maître d\'', 'Maître d\'', 1, 2, 4);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Hostess', 'Hostess', 1, 2, 4);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Waiter', 'Waiter, Waitress', 1, 2, 5);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Busser', 'Busser', 1, 2, 6);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Bartender', 'Bartender', 1, 2, 4);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Bar back', 'Bar back', 1, 2, 6);
INSERT INTO TITLE (NAME, DESCRIPTION, INDUSTRY_ID, TEAM_ID, LEVEL) VALUES ('Sommelier', 'Sommelier, Wine Steward', 1, 2, 4);

# --- !Downs

TRUNCATE TABLE TITLE;