# add GEOPOSTAL table

# --- !Ups

CREATE TABLE IF NOT EXISTS GEOPOSTAL (
  ID BIGINT(20) NOT NULL auto_increment,
  POSTALCODE VARCHAR(20) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  COUNTY VARCHAR(255) DEFAULT NULL,
  STATECODE VARCHAR(8) NOT NULL,
  COUNTRYCODE VARCHAR(2) NOT NULL,
  REGIONCODE VARCHAR(2) DEFAULT NULL,
  AREACODES VARCHAR(45) DEFAULT NULL,
  TIMEZONE VARCHAR(255) DEFAULT NULL,
  LATITUDE DOUBLE NULL,
  LONGITUDE DOUBLE NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (COUNTRYCODE) REFERENCES GEOCOUNTRY (COUNTRYCODE) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE GEOPOSTAL;