# add GEOSTATE table

# --- !Ups

CREATE TABLE IF NOT EXISTS GEOSTATE (
  ID BIGINT(20) NOT NULL auto_increment,
  COUNTRYCODE VARCHAR(2) NOT NULL,
  STATECODE VARCHAR(8) NOT NULL,
  NAME CHAR(40) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (COUNTRYCODE) REFERENCES GEOCOUNTRY (COUNTRYCODE) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE GEOSTATE;