# add GEOCITY table

# --- !Ups

CREATE TABLE IF NOT EXISTS GEOCITY (
  ID BIGINT(20) NOT NULL auto_increment,
  CITY VARCHAR(255) NOT NULL,
  COUNTY VARCHAR(255) DEFAULT NULL,
  STATECODE VARCHAR(8) NOT NULL,
  COUNTRYCODE VARCHAR(2) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (COUNTRYCODE) REFERENCES GEOCOUNTRY (COUNTRYCODE) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE GEOCITY;